aliases: now-in-commands.yml
settings:
  minimum-api: none
  use-map-color-cache: true
  allow-end: false
  warn-on-overload: false
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: -1
  query-plugins: false
  deprecated-verbose: false
  shutdown-message: Server closed
spawn-limits:
  monsters: 0
  animals: 0
  water-animals: 0
  water-ambient: 0
  water-underground-creature: 0
  axolotls: 0
  ambient: 0
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 9999999
  monster-spawns: 9999999
  water-spawns: 9999999
  water-ambient-spawns: 9999999
  water-underground-creature-spawns: 9999999
  axolotl-spawns: 9999999
  ambient-spawns: 9999999
  autosave: 0
